[package]
name = "youtube-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
youtube-client-lib = { workspace = true, features = ["audio", "download"] }
open.workspace = true
rodio.workspace = true
rusty_ytdl.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true


