[package]
name = "youtube-installer"
version = "0.1.1"
edition = "2024"
description = "Installer and setup utility for YouTube client application suite."
license = "MIT"
repository = "https://github.com/clockworkengineer/youtube-client"
readme = "../README.md"

[dependencies]
anyhow.workspace = true
youtube-client-lib = { workspace = true }
serde_json.workspace = true
